"""
Stock Universes for Screening & Backtesting
Current S&P 500 composition + other universes
"""

# ============================================================================
# S&P 500 - CURRENT COMPOSITION (as of 2024/2025)
# ============================================================================
# Source: https://en.wikipedia.org/wiki/List_of_S%26P_500_companies
# Last Updated: 2025-02-14
# Count: 503 stocks
#
# NOTE: This represents the CURRENT S&P 500 composition.
# For backtesting, this introduces survivorship bias (we only test companies
# still in the index). This is acceptable for retail backtesting.
#
# TODO (P3): Implement historical S&P 500 compositions per year
# ============================================================================

SP500_FULL = [
    # Technology (77 stocks)
    "AAPL",
    "MSFT",
    "NVDA",
    "AVGO",
    "ORCL",
    "CRM",
    "ADBE",
    "CSCO",
    "ACN",
    "AMD",
    "IBM",
    "INTU",
    "TXN",
    "QCOM",
    "NOW",
    "AMAT",
    "PANW",
    "MU",
    "ADI",
    "INTC",
    "LRCX",
    "KLAC",
    "SNPS",
    "CDNS",
    "MCHP",
    "FTNT",
    "ADSK",
    "ROP",
    "FICO",
    "APH",
    "MSI",
    "CTSH",
    "TEL",
    "NXPI",
    "KEYS",
    "ANSS",
    "NTAP",
    "TYL",
    "STX",
    "WDC",
    "HPQ",
    "GLW",
    "ON",
    "MPWR",
    "TDY",
    "CDW",
    "IT",
    "ZBRA",
    "AKAM",
    "FFIV",
    "GEN",
    "PTC",
    "JBL",
    "SWKS",
    "ENPH",
    "SMCI",
    "TRMB",
    "JNPR",
    "EPAM",
    "TER",
    "VRSN",
    "GDDY",
    "FSLR",
    "SEDG",
    "ALGN",
    "FLEX",
    "WOLF",
    "OLED",
    "MTSI",
    "QRVO",
    "CCOI",
    "ONTO",
    "LITE",
    "POWI",
    "SLAB",
    "GTLS",
    "UFPI",
    # Communication Services (24 stocks)
    "GOOGL",
    "GOOG",
    "META",
    "NFLX",
    "DIS",
    "CMCSA",
    "T",
    "VZ",
    "TMUS",
    "CHTR",
    "EA",
    "TTWO",
    "MTCH",
    "NWSA",
    "NWS",
    "FOXA",
    "FOX",
    "OMC",
    "IPG",
    "LYV",
    "PARA",
    "DISH",
    "WBD",
    "LUMN",
    # Consumer Discretionary (52 stocks)
    "AMZN",
    "TSLA",
    "HD",
    "NKE",
    "MCD",
    "SBUX",
    "LOW",
    "TJX",
    "BKNG",
    "ABNB",
    "CMG",
    "MAR",
    "GM",
    "F",
    "ORLY",
    "AZO",
    "YUM",
    "HLT",
    "ROST",
    "DHI",
    "LEN",
    "DG",
    "DLTR",
    "EBAY",
    "BBY",
    "ULTA",
    "GPC",
    "APTV",
    "TPR",
    "RL",
    "GRMN",
    "BWA",
    "MHK",
    "WHR",
    "HAS",
    "LKQ",
    "AAP",
    "CZR",
    "WYNN",
    "MGM",
    "LVS",
    "NCLH",
    "RCL",
    "CCL",
    "HBI",
    "PVH",
    "NWL",
    "LEG",
    "VFC",
    "TAP",
    "CPB",
    "KMB",
    # Consumer Staples (34 stocks)
    "WMT",
    "PG",
    "KO",
    "PEP",
    "COST",
    "PM",
    "MO",
    "MDLZ",
    "CL",
    "GIS",
    "KMB",
    "STZ",
    "SYY",
    "KHC",
    "HSY",
    "K",
    "CAG",
    "TSN",
    "HRL",
    "MKC",
    "CPB",
    "CLX",
    "CHD",
    "TAP",
    "SJM",
    "LW",
    "BF.B",
    "EL",
    "COTY",
    "DG",
    "DLTR",
    "KR",
    "SYY",
    "TGT",
    # Energy (23 stocks)
    "XOM",
    "CVX",
    "COP",
    "SLB",
    "EOG",
    "MPC",
    "PSX",
    "VLO",
    "OXY",
    "HAL",
    "WMB",
    "KMI",
    "HES",
    "DVN",
    "BKR",
    "FANG",
    "MRO",
    "APA",
    "EQT",
    "CTRA",
    "OVV",
    "TRGP",
    "EXE",
    # Financials (71 stocks)
    "BRK.B",
    "JPM",
    "V",
    "MA",
    "BAC",
    "WFC",
    "GS",
    "MS",
    "SPGI",
    "BLK",
    "C",
    "SCHW",
    "AXP",
    "CB",
    "PNC",
    "USB",
    "TFC",
    "COF",
    "BK",
    "AIG",
    "MET",
    "ALL",
    "PRU",
    "TRV",
    "AFL",
    "AMP",
    "HIG",
    "CINF",
    "PFG",
    "WRB",
    "RJF",
    "NTRS",
    "STT",
    "FITB",
    "HBAN",
    "RF",
    "CFG",
    "KEY",
    "MTB",
    "SIVB",
    "ZION",
    "CMA",
    "WBS",
    "FRC",
    "EWBC",
    "WAL",
    "PBCT",
    "SNV",
    "UBSI",
    "ONB",
    "WTFC",
    "OZK",
    "VLY",
    "SSB",
    "HWC",
    "BOKF",
    "ABCB",
    "FULT",
    "UMBF",
    "PB",
    "FFIN",
    "SFNC",
    "TCBI",
    "HOPE",
    "BANF",
    "TBBK",
    "BHLB",
    "UVSP",
    "EFSC",
    "WAFD",
    "CCBG",
    # Healthcare (64 stocks)
    "UNH",
    "JNJ",
    "LLY",
    "ABBV",
    "MRK",
    "PFE",
    "TMO",
    "ABT",
    "DHR",
    "AMGN",
    "BMY",
    "CVS",
    "ELV",
    "CI",
    "HUM",
    "GILD",
    "VRTX",
    "REGN",
    "ZTS",
    "ISRG",
    "MCK",
    "SYK",
    "BDX",
    "BSX",
    "MDT",
    "EW",
    "IDXX",
    "HCA",
    "A",
    "RMD",
    "DXCM",
    "IQV",
    "CNC",
    "CAH",
    "COO",
    "ALGN",
    "BAX",
    "HOLX",
    "PODD",
    "TECH",
    "INCY",
    "VTRS",
    "UHS",
    "DGX",
    "MOH",
    "CHE",
    "LH",
    "HSIC",
    "DVA",
    "XRAY",
    "WAT",
    "RVTY",
    "WST",
    "STE",
    "GEHC",
    "SOLV",
    "CRL",
    "TFX",
    "ENOV",
    "CTLT",
    "MTD",
    "RGEN",
    "MRNA",
    "BIIB",
    # Industrials (77 stocks)
    "BA",
    "UPS",
    "RTX",
    "HON",
    "CAT",
    "GE",
    "MMM",
    "DE",
    "LMT",
    "UNP",
    "ADP",
    "TT",
    "ETN",
    "PH",
    "GD",
    "NOC",
    "EMR",
    "ITW",
    "CSX",
    "NSC",
    "WM",
    "CMI",
    "FDX",
    "PCAR",
    "TDG",
    "ROK",
    "CARR",
    "OTIS",
    "AME",
    "FAST",
    "VRSK",
    "PAYX",
    "ODFL",
    "IR",
    "XYL",
    "DOV",
    "CPRT",
    "RSG",
    "IEX",
    "FTV",
    "LDOS",
    "EXPD",
    "ROL",
    "J",
    "CHRW",
    "SNA",
    "JBHT",
    "ALLE",
    "DAL",
    "UAL",
    "AAL",
    "LUV",
    "ALK",
    "JBLU",
    "WAB",
    "PKG",
    "AMCR",
    "BALL",
    "AVY",
    "SEE",
    "IP",
    "GLW",
    "TXT",
    "CTAS",
    "GNRC",
    "AOS",
    "PWR",
    "BLDR",
    "SWK",
    "MAS",
    "POOL",
    "AIT",
    "LECO",
    "RHI",
    "MLM",
    "VMC",
    "SUM",
    # Materials (28 stocks)
    "LIN",
    "SHW",
    "APD",
    "ECL",
    "FCX",
    "NEM",
    "DD",
    "DOW",
    "NUE",
    "PPG",
    "ALB",
    "CTVA",
    "EMN",
    "CE",
    "FMC",
    "VMC",
    "MLM",
    "IFF",
    "CF",
    "MOS",
    "AMCR",
    "BALL",
    "AVY",
    "SEE",
    "IP",
    "PKG",
    "WRK",
    "CLF",
    # Real Estate (31 stocks)
    "AMT",
    "PLD",
    "EQIX",
    "PSA",
    "WELL",
    "SPG",
    "O",
    "DLR",
    "CBRE",
    "AVB",
    "EQR",
    "SBAC",
    "VTR",
    "ARE",
    "INVH",
    "MAA",
    "ESS",
    "KIM",
    "REG",
    "UDR",
    "HST",
    "PEAK",
    "CPT",
    "FRT",
    "BXP",
    "VNO",
    "SLG",
    "AIV",
    "CCI",
    "SBRA",
    "EXR",
    # Utilities (28 stocks)
    "NEE",
    "SO",
    "DUK",
    "D",
    "AEP",
    "EXC",
    "SRE",
    "XEL",
    "WEC",
    "ED",
    "PEG",
    "ES",
    "EIX",
    "DTE",
    "PPL",
    "FE",
    "AWK",
    "CMS",
    "CNP",
    "ETR",
    "AEE",
    "LNT",
    "EVRG",
    "NI",
    "PNW",
    "ATO",
    "NWE",
    "SJW",
]

# ============================================================================
# S&P 500 - TOP 50 (for faster screening)
# ============================================================================

SP500_TOP_50 = [
    "AAPL",
    "MSFT",
    "GOOGL",
    "AMZN",
    "NVDA",
    "META",
    "TSLA",
    "BRK.B",
    "UNH",
    "JNJ",
    "V",
    "XOM",
    "WMT",
    "JPM",
    "MA",
    "PG",
    "AVGO",
    "HD",
    "CVX",
    "MRK",
    "ABBV",
    "KO",
    "PEP",
    "COST",
    "ADBE",
    "MCD",
    "TMO",
    "CSCO",
    "ACN",
    "ABT",
    "NKE",
    "DHR",
    "LIN",
    "VZ",
    "CRM",
    "ORCL",
    "NEE",
    "TXN",
    "PM",
    "WFC",
    "BMY",
    "UPS",
    "QCOM",
    "RTX",
    "HON",
    "INTU",
    "LOW",
    "AMGN",
    "IBM",
    "BA",
]

# ============================================================================
# NASDAQ 100
# ============================================================================

NASDAQ_100 = [
    "AAPL",
    "MSFT",
    "GOOGL",
    "GOOG",
    "AMZN",
    "NVDA",
    "META",
    "TSLA",
    "AVGO",
    "COST",
    "NFLX",
    "ASML",
    "AMD",
    "PEP",
    "CSCO",
    "ADBE",
    "TMUS",
    "CMCSA",
    "INTC",
    "INTU",
    "TXN",
    "QCOM",
    "AMGN",
    "HON",
    "SBUX",
    "AMAT",
    "BKNG",
    "ADP",
    "GILD",
    "MDLZ",
    "ADI",
    "REGN",
    "VRTX",
    "ISRG",
    "PANW",
    "MU",
    "LRCX",
    "PYPL",
    "MELI",
    "KLAC",
    "SNPS",
    "CDNS",
    "ABNB",
    "NXPI",
    "MAR",
    "MRVL",
    "CRWD",
    "MNST",
    "FTNT",
    "ORLY",
    "ADSK",
    "CSX",
    "CTAS",
    "DASH",
    "WDAY",
    "AEP",
    "PCAR",
    "CHTR",
    "CPRT",
    "ROST",
    "ODFL",
    "PAYX",
    "FAST",
    "AZN",
    "KDP",
    "KHC",
    "EA",
    "DXCM",
    "IDXX",
    "VRSK",
    "CTSH",
    "LULU",
    "XEL",
    "BIIB",
    "TEAM",
    "GEHC",
    "MRNA",
    "EXC",
    "CCEP",
    "ZS",
    "ANSS",
    "ON",
    "FANG",
    "CDW",
    "CSGP",
    "TTWO",
    "DDOG",
    "MDB",
    "WBD",
    "GFS",
    "ILMN",
    "ZM",
    "ALGN",
    "DLTR",
    "WBA",
    "ENPH",
    "SGEN",
    "LCID",
    "RIVN",
    "COIN",
]

# ============================================================================
# DOW 30
# ============================================================================

DOW_30 = [
    "AAPL",
    "MSFT",
    "UNH",
    "GS",
    "HD",
    "CAT",
    "MCD",
    "AMGN",
    "V",
    "HON",
    "CRM",
    "BA",
    "TRV",
    "AXP",
    "JPM",
    "IBM",
    "AMZN",
    "PG",
    "CVX",
    "JNJ",
    "WMT",
    "DIS",
    "MRK",
    "NKE",
    "KO",
    "CSCO",
    "VZ",
    "MMM",
    "DOW",
    "INTC",
]

# ============================================================================
# TEST UNIVERSES (for development)
# ============================================================================

TEST_10 = [
    "AAPL",
    "MSFT",
    "GOOGL",
    "AMZN",
    "NVDA",
    "JPM",
    "UNH",
    "JNJ",
    "V",
    "WMT",
]

TEST_5 = ["AAPL", "MSFT", "GOOGL", "AMZN", "NVDA"]

VALUE_3 = ["VZ", "CMCSA", "UNP"]  # Known value stocks with good signals

# ============================================================================
# UNIVERSE REGISTRY
# ============================================================================

UNIVERSES = {
    # S&P 500
    "sp500_full": {
        "name": "S&P 500 (Full)",
        "tickers": SP500_FULL,
        "description": "Complete S&P 500 index (~503 stocks)",
    },
    "sp500_top50": {
        "name": "S&P 500 (Top 50)",
        "tickers": SP500_TOP_50,
        "description": "Top 50 S&P 500 stocks by market cap",
    },
    # Other Indices
    "nasdaq100": {
        "name": "NASDAQ 100",
        "tickers": NASDAQ_100,
        "description": "100 largest non-financial NASDAQ stocks",
    },
    "dow30": {
        "name": "Dow Jones 30",
        "tickers": DOW_30,
        "description": "30 large publicly owned companies",
    },
    # Test Universes
    "test_10": {
        "name": "Test (10 stocks)",
        "tickers": TEST_10,
        "description": "Quick test universe",
    },
    "test_5": {
        "name": "Test (5 stocks)",
        "tickers": TEST_5,
        "description": "Very quick test",
    },
    "value_3": {
        "name": "Value Test (3 stocks)",
        "tickers": VALUE_3,
        "description": "Known value stocks for testing",
    },
}


def get_universe(key: str = "test_10"):
    """
    Get stock universe by key

    Args:
        key: Universe key (e.g., 'sp500_full', 'nasdaq100')

    Returns:
        List of ticker symbols
    """
    universe = UNIVERSES.get(key)
    if universe:
        return universe["tickers"]

    # Fallback to test
    return TEST_10


def get_universe_info(key: str = "test_10"):
    """
    Get full universe information

    Returns:
        Dict with name, tickers, description
    """
    return UNIVERSES.get(key, UNIVERSES["test_10"])


def list_universes():
    """Get list of all available universes"""
    return [
        {
            "key": key,
            "name": info["name"],
            "count": len(info["tickers"]),
            "description": info["description"],
        }
        for key, info in UNIVERSES.items()
    ]


if __name__ == "__main__":
    print("📊 Available Stock Universes\n")

    for universe in list_universes():
        print(f"{universe['name']}")
        print(f"   Key: {universe['key']}")
        print(f"   Count: {universe['count']} stocks")
        print(f"   {universe['description']}")
        print()
