repos:
  - repo: local
    hooks:
      - id: pytest
        name: Run tests
        entry: pytest
        language: system
        args: ["-v", "--tb=short", "--maxfail=1"]
        files: \.py$
        pass_filenames: false
        always_run: true
        description: "Run pytest and fail commit if any tests fail"
